-- PostgreSQL-compatible schema for db-3
-- Production schema extracted from database dump
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;
CREATE TABLE public.affiliates_affiliatelink (
ALTER TABLE public.affiliates_affiliatelink OWNER TO "zm7Jbl2hPRa0";
CREATE TABLE public.affiliates_attributiontracking (
ALTER TABLE public.affiliates_attributiontracking OWNER TO "zm7Jbl2hPRa0";
CREATE TABLE public.affiliates_catalogue (
ALTER TABLE public.affiliates_catalogue OWNER TO "zm7Jbl2hPRa0";
CREATE TABLE public.affiliates_catalogue_links (
ALTER TABLE public.affiliates_catalogue_links OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.affiliates_catalogue_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.affiliates_clicktracking (
ALTER TABLE public.affiliates_clicktracking OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.affiliates_clicktracking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.affiliates_cookieconsent (
ALTER TABLE public.affiliates_cookieconsent OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.affiliates_cookieconsent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.ai_services_aicontentlog (
ALTER TABLE public.ai_services_aicontentlog OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.ai_services_aicontentlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.ai_services_productrecommendation (
ALTER TABLE public.ai_services_productrecommendation OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.ai_services_productrecommendation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.analytics_activitylog (
ALTER TABLE public.analytics_activitylog OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.analytics_activitylog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.analytics_frauddetectionlog (
ALTER TABLE public.analytics_frauddetectionlog OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.analytics_frauddetectionlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.auth_group (
ALTER TABLE public.auth_group OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.auth_group_permissions (
ALTER TABLE public.auth_group_permissions OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.auth_permission (
ALTER TABLE public.auth_permission OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.authentication_user (
ALTER TABLE public.authentication_user OWNER TO "zm7Jbl2hPRa0";
CREATE TABLE public.authentication_user_groups (
ALTER TABLE public.authentication_user_groups OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.authentication_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.authentication_user_user_permissions (
ALTER TABLE public.authentication_user_user_permissions OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.authentication_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.commissions_commission (
ALTER TABLE public.commissions_commission OWNER TO "zm7Jbl2hPRa0";
CREATE TABLE public.commissions_payout (
ALTER TABLE public.commissions_payout OWNER TO "zm7Jbl2hPRa0";
CREATE TABLE public.commissions_payoutcommission (
ALTER TABLE public.commissions_payoutcommission OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.commissions_payoutcommission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.django_admin_log (
ALTER TABLE public.django_admin_log OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.django_celery_beat_clockedschedule (
ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.django_celery_beat_crontabschedule (
ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.django_celery_beat_intervalschedule (
ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.django_celery_beat_periodictask (
ALTER TABLE public.django_celery_beat_periodictask OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.django_celery_beat_periodictasks (
ALTER TABLE public.django_celery_beat_periodictasks OWNER TO "zm7Jbl2hPRa0";
CREATE TABLE public.django_celery_beat_solarschedule (
ALTER TABLE public.django_celery_beat_solarschedule OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.django_celery_results_chordcounter (
ALTER TABLE public.django_celery_results_chordcounter OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.django_celery_results_chordcounter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.django_celery_results_groupresult (
ALTER TABLE public.django_celery_results_groupresult OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.django_celery_results_groupresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.django_celery_results_taskresult (
ALTER TABLE public.django_celery_results_taskresult OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.django_celery_results_taskresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.django_content_type (
ALTER TABLE public.django_content_type OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.django_migrations (
ALTER TABLE public.django_migrations OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.django_session (
ALTER TABLE public.django_session OWNER TO "zm7Jbl2hPRa0";
CREATE TABLE public.notifications_notification (
ALTER TABLE public.notifications_notification OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.notifications_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.orders_cart (
ALTER TABLE public.orders_cart OWNER TO "zm7Jbl2hPRa0";
CREATE TABLE public.orders_cartitem (
ALTER TABLE public.orders_cartitem OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.orders_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.orders_customerorder (
ALTER TABLE public.orders_customerorder OWNER TO "zm7Jbl2hPRa0";
CREATE TABLE public.orders_order (
ALTER TABLE public.orders_order OWNER TO "zm7Jbl2hPRa0";
CREATE TABLE public.payments_paymentlog (
ALTER TABLE public.payments_paymentlog OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.payments_paymentlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
CREATE TABLE public.products_product (
ALTER TABLE public.products_product OWNER TO "zm7Jbl2hPRa0";
CREATE TABLE public.products_productcategory (
ALTER TABLE public.products_productcategory OWNER TO "zm7Jbl2hPRa0";
ALTER TABLE public.products_productcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
SELECT pg_catalog.setval('public.affiliates_catalogue_links_id_seq', 305, true);
SELECT pg_catalog.setval('public.affiliates_clicktracking_id_seq', 34, true);
SELECT pg_catalog.setval('public.affiliates_cookieconsent_id_seq', 1, false);
SELECT pg_catalog.setval('public.ai_services_aicontentlog_id_seq', 5, true);
SELECT pg_catalog.setval('public.ai_services_productrecommendation_id_seq', 1, false);
SELECT pg_catalog.setval('public.analytics_activitylog_id_seq', 6182, true);
SELECT pg_catalog.setval('public.analytics_frauddetectionlog_id_seq', 55, true);
SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);
SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);
SELECT pg_catalog.setval('public.auth_permission_id_seq', 140, true);
SELECT pg_catalog.setval('public.authentication_user_groups_id_seq', 1, false);
SELECT pg_catalog.setval('public.authentication_user_user_permissions_id_seq', 1, false);
SELECT pg_catalog.setval('public.commissions_payoutcommission_id_seq', 1, false);
SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);
SELECT pg_catalog.setval('public.django_celery_beat_clockedschedule_id_seq', 1, false);
SELECT pg_catalog.setval('public.django_celery_beat_crontabschedule_id_seq', 1, false);
SELECT pg_catalog.setval('public.django_celery_beat_intervalschedule_id_seq', 1, false);
SELECT pg_catalog.setval('public.django_celery_beat_periodictask_id_seq', 1, false);
SELECT pg_catalog.setval('public.django_celery_beat_solarschedule_id_seq', 1, false);
SELECT pg_catalog.setval('public.django_celery_results_chordcounter_id_seq', 1, false);
SELECT pg_catalog.setval('public.django_celery_results_groupresult_id_seq', 1, false);
SELECT pg_catalog.setval('public.django_celery_results_taskresult_id_seq', 1, false);
SELECT pg_catalog.setval('public.django_content_type_id_seq', 35, true);
SELECT pg_catalog.setval('public.django_migrations_id_seq', 70, true);
SELECT pg_catalog.setval('public.notifications_notification_id_seq', 1, false);
SELECT pg_catalog.setval('public.orders_cartitem_id_seq', 21, true);
SELECT pg_catalog.setval('public.payments_paymentlog_id_seq', 1, false);
SELECT pg_catalog.setval('public.products_productcategory_id_seq', 11, true);
ALTER TABLE ONLY public.affiliates_affiliatelink
ALTER TABLE ONLY public.affiliates_affiliatelink
ALTER TABLE ONLY public.affiliates_affiliatelink
ALTER TABLE ONLY public.affiliates_attributiontracking
ALTER TABLE ONLY public.affiliates_attributiontracking
ALTER TABLE ONLY public.affiliates_catalogue_links
ALTER TABLE ONLY public.affiliates_catalogue_links
ALTER TABLE ONLY public.affiliates_catalogue
ALTER TABLE ONLY public.affiliates_catalogue
ALTER TABLE ONLY public.affiliates_clicktracking
ALTER TABLE ONLY public.affiliates_cookieconsent
ALTER TABLE ONLY public.affiliates_cookieconsent
ALTER TABLE ONLY public.ai_services_aicontentlog
ALTER TABLE ONLY public.ai_services_productrecommendation
ALTER TABLE ONLY public.analytics_activitylog
ALTER TABLE ONLY public.analytics_frauddetectionlog
ALTER TABLE ONLY public.auth_group
ALTER TABLE ONLY public.auth_group_permissions
ALTER TABLE ONLY public.auth_group_permissions
ALTER TABLE ONLY public.auth_group
ALTER TABLE ONLY public.auth_permission
ALTER TABLE ONLY public.auth_permission
ALTER TABLE ONLY public.authentication_user
ALTER TABLE ONLY public.authentication_user_groups
ALTER TABLE ONLY public.authentication_user_groups
ALTER TABLE ONLY public.authentication_user
ALTER TABLE ONLY public.authentication_user_user_permissions
ALTER TABLE ONLY public.authentication_user_user_permissions
ALTER TABLE ONLY public.commissions_commission
ALTER TABLE ONLY public.commissions_payout
ALTER TABLE ONLY public.commissions_payoutcommission
ALTER TABLE ONLY public.commissions_payoutcommission
ALTER TABLE ONLY public.django_admin_log
ALTER TABLE ONLY public.django_celery_beat_clockedschedule
ALTER TABLE ONLY public.django_celery_beat_crontabschedule
ALTER TABLE ONLY public.django_celery_beat_intervalschedule
ALTER TABLE ONLY public.django_celery_beat_periodictask
ALTER TABLE ONLY public.django_celery_beat_periodictask
ALTER TABLE ONLY public.django_celery_beat_periodictasks
ALTER TABLE ONLY public.django_celery_beat_solarschedule
ALTER TABLE ONLY public.django_celery_beat_solarschedule
ALTER TABLE ONLY public.django_celery_results_chordcounter
ALTER TABLE ONLY public.django_celery_results_chordcounter
ALTER TABLE ONLY public.django_celery_results_groupresult
ALTER TABLE ONLY public.django_celery_results_groupresult
ALTER TABLE ONLY public.django_celery_results_taskresult
ALTER TABLE ONLY public.django_celery_results_taskresult
ALTER TABLE ONLY public.django_content_type
ALTER TABLE ONLY public.django_content_type
ALTER TABLE ONLY public.django_migrations
ALTER TABLE ONLY public.django_session
ALTER TABLE ONLY public.notifications_notification
ALTER TABLE ONLY public.orders_cart
ALTER TABLE ONLY public.orders_cartitem
ALTER TABLE ONLY public.orders_cartitem
ALTER TABLE ONLY public.orders_customerorder
ALTER TABLE ONLY public.orders_customerorder
ALTER TABLE ONLY public.orders_customerorder
ALTER TABLE ONLY public.orders_order
ALTER TABLE ONLY public.orders_order
ALTER TABLE ONLY public.orders_order
ALTER TABLE ONLY public.payments_paymentlog
ALTER TABLE ONLY public.payments_paymentlog
ALTER TABLE ONLY public.products_product
ALTER TABLE ONLY public.products_product
ALTER TABLE ONLY public.products_product
ALTER TABLE ONLY public.products_productcategory
ALTER TABLE ONLY public.products_productcategory
ALTER TABLE ONLY public.products_productcategory
CREATE INDEX affiliates_affiliatelink_marketer_id_8368ee38 ON public.affiliates_affiliatelink USING btree (marketer_id);
CREATE INDEX affiliates_affiliatelink_product_id_4d93003c ON public.affiliates_affiliatelink USING btree (product_id);
CREATE INDEX affiliates_affiliatelink_unique_slug_a83eec5d_like ON public.affiliates_affiliatelink USING btree (unique_slug varchar_pattern_ops);
CREATE INDEX affiliates_attributiontracking_cookie_id_a9f7dbcc_like ON public.affiliates_attributiontracking USING btree (cookie_id varchar_pattern_ops);
CREATE INDEX affiliates_attributiontracking_first_click_link_id_a23746b4 ON public.affiliates_attributiontracking USING btree (first_click_link_id);
CREATE INDEX affiliates_attributiontracking_last_click_link_id_e623fb8c ON public.affiliates_attributiontracking USING btree (last_click_link_id);
CREATE INDEX affiliates_attributiontracking_order_id_c2be36e2 ON public.affiliates_attributiontracking USING btree (order_id);
CREATE INDEX affiliates_catalogue_links_affiliatelink_id_c280364c ON public.affiliates_catalogue_links USING btree (affiliatelink_id);
CREATE INDEX affiliates_catalogue_links_catalogue_id_6ec00507 ON public.affiliates_catalogue_links USING btree (catalogue_id);
CREATE INDEX affiliates_catalogue_marketer_id_84d28156 ON public.affiliates_catalogue USING btree (marketer_id);
CREATE INDEX affiliates_catalogue_slug_d4286318_like ON public.affiliates_catalogue USING btree (slug varchar_pattern_ops);
CREATE INDEX affiliates_clicktracking_link_id_2fa9cdbf ON public.affiliates_clicktracking USING btree (link_id);
CREATE INDEX affiliates_cookieconsent_cookie_id_188ffadb_like ON public.affiliates_cookieconsent USING btree (cookie_id varchar_pattern_ops);
CREATE INDEX ai_services_aicontentlog_product_id_1eb0a388 ON public.ai_services_aicontentlog USING btree (product_id);
CREATE INDEX ai_services_aicontentlog_user_id_b5a542af ON public.ai_services_aicontentlog USING btree (user_id);
CREATE INDEX ai_services_productrecommendation_marketer_id_d3f31afa ON public.ai_services_productrecommendation USING btree (marketer_id);
CREATE INDEX ai_services_productrecommendation_product_id_a58fc365 ON public.ai_services_productrecommendation USING btree (product_id);
CREATE INDEX analytics_activitylog_user_id_d7739206 ON public.analytics_activitylog USING btree (user_id);
CREATE INDEX analytics_frauddetectionlog_reviewed_by_id_af2d2700 ON public.analytics_frauddetectionlog USING btree (reviewed_by_id);
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);
CREATE INDEX authentication_user_email_2220eff5_like ON public.authentication_user USING btree (email varchar_pattern_ops);
CREATE INDEX authentication_user_groups_group_id_6b5c44b7 ON public.authentication_user_groups USING btree (group_id);
CREATE INDEX authentication_user_groups_user_id_30868577 ON public.authentication_user_groups USING btree (user_id);
CREATE INDEX authentication_user_user_permissions_permission_id_ea6be19a ON public.authentication_user_user_permissions USING btree (permission_id);
CREATE INDEX authentication_user_user_permissions_user_id_736ebf7e ON public.authentication_user_user_permissions USING btree (user_id);
CREATE INDEX commissions_commission_marketer_id_69035b84 ON public.commissions_commission USING btree (marketer_id);
CREATE INDEX commissions_commission_order_id_a133354d ON public.commissions_commission USING btree (order_id);
CREATE INDEX commissions_commission_payout_id_c1a19b2d ON public.commissions_commission USING btree (payout_id);
CREATE INDEX commissions_commission_product_id_7c16fdee ON public.commissions_commission USING btree (product_id);
CREATE INDEX commissions_payout_marketer_id_31838f07 ON public.commissions_payout USING btree (marketer_id);
CREATE INDEX commissions_payoutcommission_commission_id_d21e7e34 ON public.commissions_payoutcommission USING btree (commission_id);
CREATE INDEX commissions_payoutcommission_payout_id_31c2feef ON public.commissions_payoutcommission USING btree (payout_id);
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);
CREATE INDEX django_cele_date_cr_bd6c1d_idx ON public.django_celery_results_groupresult USING btree (date_created);
CREATE INDEX django_cele_date_cr_f04a50_idx ON public.django_celery_results_taskresult USING btree (date_created);
CREATE INDEX django_cele_date_do_caae0e_idx ON public.django_celery_results_groupresult USING btree (date_done);
CREATE INDEX django_cele_date_do_f59aad_idx ON public.django_celery_results_taskresult USING btree (date_done);
CREATE INDEX django_cele_periodi_1993cf_idx ON public.django_celery_results_taskresult USING btree (periodic_task_name);
CREATE INDEX django_cele_status_9b6201_idx ON public.django_celery_results_taskresult USING btree (status);
CREATE INDEX django_cele_task_na_08aec9_idx ON public.django_celery_results_taskresult USING btree (task_name);
CREATE INDEX django_cele_worker_d54dd8_idx ON public.django_celery_results_taskresult USING btree (worker);
CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);
CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);
CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);
CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);
CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);
CREATE INDEX django_celery_results_chordcounter_group_id_1f70858c_like ON public.django_celery_results_chordcounter USING btree (group_id varchar_pattern_ops);
CREATE INDEX django_celery_results_groupresult_group_id_a085f1a9_like ON public.django_celery_results_groupresult USING btree (group_id varchar_pattern_ops);
CREATE INDEX django_celery_results_taskresult_task_id_de0d95bf_like ON public.django_celery_results_taskresult USING btree (task_id varchar_pattern_ops);
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);
CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);
CREATE INDEX notifications_notification_user_id_b5e8c0ff ON public.notifications_notification USING btree (user_id);
CREATE INDEX orders_cart_buyer_id_66236b2e ON public.orders_cart USING btree (buyer_id);
CREATE INDEX orders_cartitem_cart_id_529df5fa ON public.orders_cartitem USING btree (cart_id);
CREATE INDEX orders_cartitem_product_id_55063ee7 ON public.orders_cartitem USING btree (product_id);
CREATE INDEX orders_customerorder_buyer_id_4125f380 ON public.orders_customerorder USING btree (buyer_id);
CREATE INDEX orders_customerorder_order_number_9df7bfd5_like ON public.orders_customerorder USING btree (order_number varchar_pattern_ops);
CREATE INDEX orders_customerorder_payment_reference_611e3188_like ON public.orders_customerorder USING btree (payment_reference varchar_pattern_ops);
CREATE INDEX orders_order_customer_order_id_9c6a2a59 ON public.orders_order USING btree (customer_order_id);
CREATE INDEX orders_order_marketer_id_7800a889 ON public.orders_order USING btree (marketer_id);
CREATE INDEX orders_order_order_number_4e985f70_like ON public.orders_order USING btree (order_number varchar_pattern_ops);
CREATE INDEX orders_order_payment_reference_bd447c88_like ON public.orders_order USING btree (payment_reference varchar_pattern_ops);
CREATE INDEX orders_order_product_id_096244de ON public.orders_order USING btree (product_id);
CREATE INDEX orders_order_seller_id_9df17eb1 ON public.orders_order USING btree (seller_id);
CREATE INDEX payments_paymentlog_reference_3011e0c1_like ON public.payments_paymentlog USING btree (reference varchar_pattern_ops);
CREATE INDEX products_product_category_id_9b594869 ON public.products_product USING btree (category_id);
CREATE INDEX products_product_seller_id_07afb1e3 ON public.products_product USING btree (seller_id);
CREATE INDEX products_product_sku_3c51a516_like ON public.products_product USING btree (sku varchar_pattern_ops);
CREATE INDEX products_product_slug_70d3148d_like ON public.products_product USING btree (slug varchar_pattern_ops);
CREATE INDEX products_productcategory_name_dad35cfe_like ON public.products_productcategory USING btree (name varchar_pattern_ops);
CREATE INDEX products_productcategory_parent_id_37f1f851 ON public.products_productcategory USING btree (parent_id);
CREATE INDEX products_productcategory_slug_90cb01f3_like ON public.products_productcategory USING btree (slug varchar_pattern_ops);
ALTER TABLE ONLY public.affiliates_affiliatelink
ALTER TABLE ONLY public.affiliates_affiliatelink
ALTER TABLE ONLY public.affiliates_attributiontracking
ALTER TABLE ONLY public.affiliates_attributiontracking
ALTER TABLE ONLY public.affiliates_attributiontracking
ALTER TABLE ONLY public.affiliates_catalogue_links
ALTER TABLE ONLY public.affiliates_catalogue_links
ALTER TABLE ONLY public.affiliates_catalogue
ALTER TABLE ONLY public.affiliates_clicktracking
ALTER TABLE ONLY public.ai_services_aicontentlog
ALTER TABLE ONLY public.ai_services_aicontentlog
ALTER TABLE ONLY public.ai_services_productrecommendation
ALTER TABLE ONLY public.ai_services_productrecommendation
ALTER TABLE ONLY public.analytics_activitylog
ALTER TABLE ONLY public.analytics_frauddetectionlog
ALTER TABLE ONLY public.auth_group_permissions
ALTER TABLE ONLY public.auth_group_permissions
ALTER TABLE ONLY public.auth_permission
ALTER TABLE ONLY public.authentication_user_user_permissions
ALTER TABLE ONLY public.authentication_user_groups
ALTER TABLE ONLY public.authentication_user_user_permissions
ALTER TABLE ONLY public.authentication_user_groups
ALTER TABLE ONLY public.commissions_commission
ALTER TABLE ONLY public.commissions_commission
ALTER TABLE ONLY public.commissions_commission
ALTER TABLE ONLY public.commissions_commission
ALTER TABLE ONLY public.commissions_payout
ALTER TABLE ONLY public.commissions_payoutcommission
ALTER TABLE ONLY public.commissions_payoutcommission
ALTER TABLE ONLY public.django_admin_log
ALTER TABLE ONLY public.django_admin_log
ALTER TABLE ONLY public.django_celery_beat_periodictask
ALTER TABLE ONLY public.django_celery_beat_periodictask
ALTER TABLE ONLY public.django_celery_beat_periodictask
ALTER TABLE ONLY public.django_celery_beat_periodictask
ALTER TABLE ONLY public.notifications_notification
ALTER TABLE ONLY public.orders_cart
ALTER TABLE ONLY public.orders_cartitem
ALTER TABLE ONLY public.orders_cartitem
ALTER TABLE ONLY public.orders_customerorder
ALTER TABLE ONLY public.orders_order
ALTER TABLE ONLY public.orders_order
ALTER TABLE ONLY public.orders_order
ALTER TABLE ONLY public.orders_order
ALTER TABLE ONLY public.products_product
ALTER TABLE ONLY public.products_product
ALTER TABLE ONLY public.products_productcategory
